FROM debian:bullseye-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN set -eux; apt-get update; \
    apt-get --assume-yes install \
    apt-utils \
    ; \
    apt-get --assume-yes autoremove; \
    apt-get --assume-yes clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    # This rm statement follows this:
    # https://github.com/debuerreotype/debuerreotype/blob/master/scripts/.slimify-excludes
    rm -rf /usr/share/doc/* /usr/share/info/* /usr/share/linda/* \
    /usr/share/lintian/overrides/* /usr/share/locale/* \
    /usr/share/man/* /usr/share/doc/kde/HTML/*/* \
    /usr/share/gnome/help/*/* /usr/share/locale/* \
    /usr/share/omf/*/*-*.emf

# Update installed packages
RUN set -eux; apt-get update; \
    apt-get --assume-yes upgrade --no-install-recommends; \
    apt-get --assume-yes autoremove; \
    apt-get --assume-yes clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    # This rm statement follows this:
    # https://github.com/debuerreotype/debuerreotype/blob/master/scripts/.slimify-excludes
    rm -rf /usr/share/doc/* /usr/share/info/* /usr/share/linda/* \
    /usr/share/lintian/overrides/* /usr/share/locale/* \
    /usr/share/man/* /usr/share/doc/kde/HTML/*/* \
    /usr/share/gnome/help/*/* /usr/share/locale/* \
    /usr/share/omf/*/*-*.emf

# Install some additional helpful packages
RUN set -eux; apt-get update; \
    apt-get --assume-yes install \
    iproute2 \
    iputils-ping \
    iputils-tracepath \
    nano-tiny \
    tree \
    ; \
    apt-get --assume-yes autoremove; \
    apt-get --assume-yes clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    # This rm statement follows this:
    # https://github.com/debuerreotype/debuerreotype/blob/master/scripts/.slimify-excludes
    rm -rf /usr/share/doc/* /usr/share/info/* /usr/share/linda/* \
    /usr/share/lintian/overrides/* /usr/share/locale/* \
    /usr/share/man/* /usr/share/doc/kde/HTML/*/* \
    /usr/share/gnome/help/*/* /usr/share/locale/* \
    /usr/share/omf/*/*-*.emf

