version: "3.9"

services:
  debian_bullseye:
    container_name: bullseye
    image: alemna/debian:bullseye
    build:
      context: ./bullseye
      dockerfile: Dockerfile
      args:
        - VARIANT=bullseye
  debian_bullseye_slim:
    container_name: bullseye-slim
    image: alemna/debian:bullseye-slim
    build:
      context: ./bullseye
      dockerfile: Dockerfile
      args:
        - VARIANT=bullseye-slim

  debian_user:
    container_name: user
    image: alemna/debian:user
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      debian_bullseye:
        condition: service_completed_successfully
