name: Update repository

# Controls when the workflow will run
on:
  schedule:
    - cron: '50 6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Github Actions user in Git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make sure setup is executable
        run: chmod +x ./setup.sh
  
      - name: Run setup
        run: ./setup.sh
      
      - name: Build debian
        run: |
          bash ./bigtree debian code --fetch --merge
          bash _helpers/debian.sh

  build-python:
    runs-on: ubuntu-latest
    needs: build-python
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Github Actions user in Git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make sure setup is executable
        run: chmod +x ./setup.sh
  
      - name: Run setup
        run: ./setup.sh
      
      - name: Build python
        run: |
          bash ./bigtree python code --fetch --merge
          bash _helpers/python.sh
  
  build-write:
    runs-on: ubuntu-latest
    needs: build-python
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Github Actions user in Git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make sure setup is executable
        run: chmod +x ./setup.sh
  
      - name: Run setup
        run: ./setup.sh

      - name: Build write
        run: |
          bash ./bigtree write code --fetch --merge --add write
          bash _helpers/write.sh
